### ISSUE TITLE
Support optional secrets

### ISSUE THREAD

**Issue by dgrove-oss** [IBM/solsa#13]
Need to support secrets being optional

```
          - name: KAFKA_API_KEY
            valueFrom:
              secretKeyRef:
                name: kafka
                key: api-key
                optional: true
```
