### ISSUE TITLE
ContainerizedService: VolumeMounts

### ISSUE THREAD

**Issue by dgrove-oss** [IBM/solsa#14]
Need to be able to support mounting secrets and configmaps as volumes

```
volumeMounts:
     - mountPath: /keystores
       name: kafka-keystore-volume
       readOnly: true
volumes:
   - name: kafka-keystore-volume
      secret:
     secretName: kafka-keystore
```
